version: '3'
services:
  web:
    image: ambae:latest
    ports:
      - "9000:8080" 
    environment:
      - "SPRING_PROFILES_ACTIVE=h2"
    depends_on: 
      - redis # start that first
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  redis:
    image: "redis:alpine"
    #ports:
    #  - "6379:6379"
    networks:
      - backend  

networks:
  backend: