CREATE TABLE reservation (
	id BIGSERIAL PRIMARY KEY,
	start_date TIMESTAMP WITH TIME ZONE NOT NULL,
	end_date TIMESTAMP WITH TIME ZONE NOT NULL,
	email VARCHAR(256) NOT NULL,
	first_name VARCHAR(256),
	last_name VARCHAR(256) NOT NULL,
	created TIMESTAMP WITH TIME ZONE
);

CREATE TABLE reservation_key (
	id BIGSERIAL PRIMARY KEY,
	date_key VARCHAR(32) UNIQUE NOT NULL,
	reservation_id BIGINT NOT NULL
);
